### ISSUE TITLE
🐛When opening Live Execution Tracker from Inspect's Dashboard the ActiveSolution/ActiveDiagram is not set.

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/bpmn-studio#1187]
#### Describe your issue

<img width="922" alt="bildschirmfoto 2018-12-12 um 09 26 02" src="https://user-images.githubusercontent.com/17065920/49856463-20426280-fdf0-11e8-9e8b-f07aee4a7c78.png">

The ActiveSolutiom and ActiveDiagram should be set when opening the Live Execution Tracker because after executing some tasks, maybe you want to navigate to the inspect correlation or design view and the wrong diagram is selected then.

Otherwise, the behavior may lead to confusion.

#### How can others reproduce the issue?

- select a diagram
- goto inspect dashbboard
- open the live execution tracker of another running process
- complete some tasks for e.g.
- now click on inspect to look up your tokens e.g.
- see that there is not selected you diagram you have worked with

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [ ] I've checked if this issue already exists
- [ ] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one
